version: '3.9'

services:

  postgres-db:
    image: postgres:14.3-alpine
    ports:
      - target: 5432
        published: 12345
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: com3014db
