version: '3.9'

services:

  postgres-db:
    image: postgres:14.3-alpine
    ports:
      - target: ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:7.2-alpine
    ports:
      - target: ${REDIS_PORT}
    command: >
          --requirepass ${REDIS_PASSWORD}

  user-api:
    build: ./user-api
    depends_on:
      - postgres-db
      - redis
    ports:
      - target: 8080
        published: 8081
    environment:
      DB_URL: jdbc:postgresql://postgres-db:${DB_PORT}/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CORS_PERMITTED_URLS: http://localhost:4000/

  frontend:
    build:
      context: ./frontend
      args:
        VITE_USER_API_URL: http://localhost:8081/api
    ports:
      - target: 8080
        published: 4000
